services:
  matrixa-sudby-ru:
    image: aristockij/taro-image-ru:latest
    container_name: matrixa-sudby-ru
    restart: always
    networks:
      - web
   
  mystic-uslugi-ru:
    image: aristockij/taro-matrix-ru:latest
    container_name: mystic-uslugi-ru
    restart: always
    networks:
      - web    
    

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - matrixa-sudby-ru
      - mystic-uslugi-ru

    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs:ro
    networks:
      - web

networks:
  web:
    driver: bridge